name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Build and publish app
      run: dotnet publish -c Release -o release --nologo

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        guthub_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: release/wwwroot
